language: ruby
before_install:
    - brew update
install:
    - mkdir -p $(brew --repo)/Library/Taps/travis
    - ln -s $PWD $(brew --repo)/Library/Taps/travis/homebrew-moira
    - brew tap --repair
env: PACKAGE=moira
script:
    - brew audit $PACKAGE
    - brew install -v $PACKAGE
    - brew test $PACKAGE
matrix:
    include:
        - env: macos=10.13
          os: osx
          osx_image: xcode9.1
          rvm: system
        - env: macos=10.12
          os: osx
          osx_image: xcode8.3
          rvm: system
        - env: macos=10.11
          os: osx
          osx_image: xcode7.3
          rvm: system
        - env: macos=10.10
          os: osx
          osx_image: xcode6.4
          rvm: system